# Site settings
title: G S Deepak Kumar
description: Portfolio of G S Deepak Kumar
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: G S Deepak Kumar
user_description: Result driven professional with nearly 2 years of experience as a product development executive with reputed tier 1 automotive company.In the past two years,I have handled some high profile projects for multiple domestic and export customers.I relish on the responsibility the project entities and can deliver a defined set of work without supervision.Currently pursuing Post Graduate Program in Business Analytics & Business Intelligence.Possess Knowledge on Statistics,Exploratory Data analysis and report writing.
user_title: Business Analyst 
email: gsdeepakkumar@gmail.com
linkedin_username: g s deepak kumar
github_username: Deepak Kumar G S 


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
